"""empty message

Revision ID: d2352eafcd49
Revises: 409d737ae1f0
Create Date: 2024-04-22 19:43:15.595950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2352eafcd49'
down_revision = '409d737ae1f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_creator', schema=None) as batch_op:
        batch_op.drop_column('name')

    with op.batch_alter_table('favorite_game', schema=None) as batch_op:
        batch_op.drop_column('name')

    with op.batch_alter_table('favorite_store', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_store', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=False))

    with op.batch_alter_table('favorite_game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=False))

    with op.batch_alter_table('favorite_creator', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
