"""empty message

Revision ID: e7f30f7cb2a0
Revises: 2c5ca2c16568
Create Date: 2024-04-30 17:43:12.343517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7f30f7cb2a0'
down_revision = '2c5ca2c16568'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorite_store')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite_store',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('store_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='favorite_store_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='favorite_store_pkey')
    )
    # ### end Alembic commands ###
